### ISSUE TITLE
Ceph RBD rollback image

### ISSUE THREAD

**Issue by BadKid90s** [ceph/go-ceph#1014]
How to determine if Ceph RBD rollback image is successful?
﻿
How to determine if the rollback is successful using the command line or HTTP API?

**Comment by phlogistonjohn** [comment]
Are you asking if how to tell if the function https://github.com/ceph/go-ceph/blob/d564eff5238666e05b7ed8e3442c3d4e136b860b/rbd/snapshot.go#L88 succeeded?

On an API level you should be checking the `error` is not nil. If you mean on some sort of higher level, you'd probably have to build something like a function that checksums an image before snapshotting and then verifies it after rollback.  If you asking for something even more than that I suggest talking to the Ceph team directly because go-ceph is focused on making the Ceph APIs available, not making sure they work.

I don't really know what command line or HTTP you might be referring to. Again, if you're looking for general Ceph help you may want to try the ceph lists: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/

**Comment by BadKid90s** [comment]
Perform a checksum on the image before the snapshot, and then validate it after the rollback. How should it be operated? How to calculate the comparative checksum?

**Comment by phlogistonjohn** [comment]
If I was going to implement that I would use the [image read apis](https://pkg.go.dev/github.com/ceph/go-ceph/rbd#Image.Read) to copy the bytes into one of Go's hash algorithms like [sha256](https://pkg.go.dev/crypto/sha256#New).

Just as a reminder go-ceph provides the Ceph apis as a golang library, what you do with those apis is up to you. So take my suggestion above with a grain of salt, because I really don't know what your ultimate goal is. :-)
