### ISSUE TITLE
Please update ceph documentation with Golang instructions

### ISSUE THREAD

**Issue by rleiwang** [ceph/go-ceph#121]
I found out it is really hard as a Golang developer to use Ceph on MacOS. The instructions listed here don't compile on Mac. Documentation on how to use Amazon S3 Go SDK https://docs.ceph.com/docs/nautilus/radosgw/s3/ doesn't exist. Luckily, i found really good instructions elsewhere, https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-go-with-minio.md.

**Comment by phlogistonjohn** [comment]
I'm sorry but I don't know what you are referring to. Can you please be more specific?
I'll admit the project is Linux oriented, and we would certainly consider improving the workflow on Mac, but Mac users would need to contribute said improvements.

**Comment by nixpanic** [comment]
Hi @rleiwang,

this project offers Golang bindings for Ceph native libraries. The bindings can be used to communicate with Ceph directly. Ceph does not use S3 internally, but offers RGW as an addon so that S3 clients can be used to store/retrieve data from Ceph. The Golang bindings do not offer S3 features, for that you should be able to use any S3 Golang package. It is beyond this project to explain how to setup and configure Ceph RGW.

Does this explain things a little better? Let us know if it all makes more sense, or if there are any further questions.

Thanks!

**Comment by phlogistonjohn** [comment]
@rleiwang I hope that the previous comments help you regarding use of RGW/S3 apis. As this issue has been idle for over a month without confirmation I'm closing it. Please feel free to reopen it if you wish to discuss things more.
