### ISSUE TITLE
MakePool with custom configuration

### ISSUE THREAD

**Issue by hxquangnhat** [ceph/go-ceph#140]
How to create pool with the custom settings, not the default one?

I tried to create a pool with my custom `pg_num` and `pgp_num` via setting them with `SetConfigOption` but it didn't seem to work as it always created the pool with default `pg_num` and `pgp_num` (8).

**Comment by phlogistonjohn** [comment]
Hi @hxquangnhat I briefly skimmed some of the api docs for librados and rados_pool_create is labeled "Create a pool with default settings" and "The default crush rule is rule 0" so I'm not sure you can create custom values that way with create pool.
There's a rados_pool_create_with_crush_rule function that we don't currently wrap that might help but I'll admit that I'm not certain it will. If you can access this functionality using ceph cli tools can you please record them here and we can research what api calls the cli makes and determine if this is something we can provide in our api.

**Comment by phlogistonjohn** [comment]
I spent some time recently digging into how the 'ceph' cli tool creates pools. It turns out that the "MakePool" librados function is not used for this operation. Rather it uses the mon command functionality to send a json formatted command to create the pool.
I figured this out by tracing and reading the python code used by the `ceph` command line tool. Again, I won't claim this is optimal but you can do the equivalent in go using this library with something like the following:
```go
mc := []byte(`{"prefix": "osd pool create", "pool": "bob", "pg_num": "32"}`)
buf, info, err := conn.MonCommand(mc)
```
All the arguments that `ceph osd pool create ...` supports can be added to the json you just need to determine what the keys are. If you pass the command prefix as "get_command_descriptions" you will get json that you can scrape to determine the exact arguments the commands (all of them actually) support.

One annoying difference I noticed using this method versus MakePool was that it does not return an error if the pool name is already in use. If you care about that you may want to scrape the string returned in buf or some other check.

**Comment by phlogistonjohn** [comment]
Hopefully my answer from about a month ago is sufficient. It allows a user of the lib to create a pool the same way the ceph command line tool does. Since there's been no followup over that month I'm closing this issue. Feel free to reopen if additional discussion is needed.
