### ISSUE TITLE
build error: could not determine kind of name for C.rados_read_op_omap_get_vals2

### ISSUE THREAD

**Issue by iawia002** [ceph/go-ceph#144]
Hi there, I'm trying to build this on `arm64v8/debian:stretch` and then got this error:

```
vendor/github.com/ceph/go-ceph/rados/ioctx.go:453:2: could not determine kind of name for C.rados_read_op_omap_get_vals2
```

Any ideas?

Ceph version: luminous

**Comment by nixpanic** [comment]
This has been introduced with #80, commit 7884e8a8af2d06baee9c38143a8c236783459e60.

The function that can not be found (`rados_read_op_omap_get_vals2`) has been introduced with ceph/ceph@fbebd83537b66b19d51c68e2fd51359305e84a3b and is part of Ceph v12.0.0, which would be Luminous.

Automated tests in Travis CI of go-ceph also run against Luminous. It is unclear to me why you get the build error. Can you share a complete log of the installation of development package and the build process?

**Comment by iawia002** [comment]
Sorry, my bad, I plan to install the luminous version, but somehow it was v10.x version in the end. After installing the luminous version correctly, there is no build error anymore.

**Comment by jafernaqvi** [comment]
Hi, 
I get this error when i try to perform any rbd level operation through the client library such as getting image names( GetImageNames(ioctx) ).... 
```
../../go/pkg/mod/github.com/ceph/go-ceph@v0.3.0/rbd/features_mimic.go:15:26: could not determine kind of name for C.RBD_FEATURE_NAME_OPERATIONS
../../go/pkg/mod/github.com/ceph/go-ceph@v0.3.0/rbd/features_mimic.go:11:29: could not determine kind of name for C.RBD_FEATURE_OPERATIONS
```
ceph version: Nautilus
Can anyone guide me on how to resolve this?

**Comment by phlogistonjohn** [comment]
Both of those constants should be available on ceph versions mimic and later. I would double check that the version of the libraries where you are building is in fact, nautilus. You can also try changing the build tags (`-tags nautilus` or `-tags luminous` etc). Currently we have tags for "luminous", "mimic", "nautilus", and "octopus". 

PS. In the future please file a new issue rather than commenting on a closed issue unless you are sure its the same. IMO, It's easier to cross-link separate issues that end up being the same than splitting an issue up later.

**Comment by jafernaqvi** [comment]
Thanks,
And okay i will keep that in mind...
