### ISSUE TITLE
rbd: Add support for setting image features introduced with Mimic and Nautilus

### ISSUE THREAD

**Issue by nixpanic** [ceph/go-ceph#183]
There are new image features that can be enable with Mimic and Nautilus. With support for building against different Ceph versions, these new features can now be enabled/skipped during compilation.

Work in progress is at [nixpanic/go-ceph#wip/rbd/features](https://github.com/nixpanic/go-ceph/tree/wip/rbd/features).

**Comment by phlogistonjohn** [comment]
I took a quick peek at your branch there. The "thick" patch piqued my interest.
I created the following to demonstrate some ideas that looking at it raised:
https://play.golang.org/p/2XVglL0dm6e
The two big points are: using the properties of maps to our benefit, and using a conversion function rather than an additional GetFeatuesXYZ helper. All of this is just a suggestion/brainstorming.

**Comment by nixpanic** [comment]
I was not happy with the thick API yet, so I didn't post a PR for it yet. Your suggestion is a good idea, and it sticks closer to the librbd API without introducing the weird `Feature {string, int}` type.
