### ISSUE TITLE
Issues with connection timeout and memory consumption

### ISSUE THREAD

**Issue by hairesis** [ceph/go-ceph#223]
Hi all,
I'm implementing an Hashicorp Vault plugin to retrieve ceph keys from it. Being a long running application and potentially serving multiple concurrent requests I thought at implementing a connection pool. A gist of a raw implementation inspired from the implementation in ceph-csi can be found here: https://gist.github.com/hairesis/cc17cfaadba3ed48d4fb68c838aaddfb.

Questions are:
1) I could not figure out what was the right command line option to pass to set connection timeout. 
2) What's the best way to react to a connection reset?
3) Every time I dispose a new connection and subsequently create a new one, or simply keep a connection active over time, my RSS seems to slowing creeping up. Is there something I'm doing wrong/missing?

Thanks!

**Comment by nixpanic** [comment]
1. I do not think there is a way to pass a connection timeout
  The ceph-csi implemetation just keeps the last active connection around, and destroys it after a timeout when is has not been used. Because the connection is used for management operations (not I/O), it is not (yet) expected that multiple connections with the same credentials/cluster are needed.
1. When there is a connection reset, it might be handled by librados or other core Ceph functions already. If those do not restore functionality, the connection should probably forcefully be destroyed so that a new connection can be created.
1. librados starts a Ceph client that is quite resource hungry, with multiple threads and other allocations. You might be hitting a resource leak. I suggest to validate the number of connections that you have, number of connections you destroy and the amount of memory that the application grows when idle. Maybe just a simple reproducing program, without any functionality that connects and destroys connections in a loop? Check the number of threads (both Go and native), and maybe consider adding [pprof](https://github.com/google/pprof/blob/master/doc/README.md) through a [http listener](https://golang.org/pkg/net/http/pprof/)

Please keep us informed about the progress you make. Thanks and good luck!

**Comment by phlogistonjohn** [comment]
This issue is 4 months stale at this point. Closing. Feel free to reopen the issue if you need to. Thanks.
