### ISSUE TITLE
use go-ceph for windows:question

### ISSUE THREAD

**Issue by foroughmajidi** [ceph/go-ceph#368]
Does go-ceph work on windows?

**Comment by phlogistonjohn** [comment]
Maybe? I don't think anyone has tried it yet. Since go-ceph is not pure go, but links to ceph libs, it heavily depends on if the parts of ceph that we need work on Windows as well. I do think that both Go and cgo should work in theory.
Currently, all of the maintainers are focused on Linux environments but we'd be happy to have contributions to build and test on Windows from any interested party.

**Comment by foroughmajidi** [comment]
Thanks for your response .
we don't have librados on windows so I can't use ceph-go.Is this  true?
do you any suggestion for me?

**Comment by phlogistonjohn** [comment]
As of today I think that is true, yes.

Not knowing much about your intended use case it is hard for me to speculate, but in the short term you might look into a layer like WSL or running containers/docker on windows and run go-ceph based programs that way.


Longer term I do remember about hearing of at least one effort to make ceph portable to Windows. I remember seeing patches but cannot find it at the moment. If that came true, in theory, someone could build go-ceph against it. But I have no idea how likely this would be.
