### ISSUE TITLE
cephfs: RetainSnapshots flag is not passed properly

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#451]
Looks like "--retain-snapshots" flag is not getting set using go-ceph API**
https://github.com/ceph/ceph-csi/issues/1845

**Comment by agarwal-mudit** [comment]
cc @madhu-1 @nixpanic

**Comment by agarwal-mudit** [comment]
@phlogistonjohn Sorry for opening single issue for multiple things. Will send separate PRs.

**Comment by agarwal-mudit** [comment]
Today, we ignore BytesQuota if it is infinite ([here](https://github.com/openshift/ceph-csi/blob/bccd5cef46044151443dab5d58bf0f7d04e334a0/internal/cephfs/volume.go#L109)). We can also ignore if it is nil (in case where subvolume is deleted with retained snapshots) to solve https://github.com/ceph/ceph-csi/issues/1845 or we can check state field and if it is "snapshot-retained" then we can ignode bytes_quota field.
That is the use case for "state" attribute mentioned in the description.

**Comment by phlogistonjohn** [comment]
Sorry, but I am having a bit of trouble parsing this issue.
First off, are there three (or more) independent issues here? If so, we really ought to have three issues (one for problem).

> This includes "state" attribute also but SubVolumeInfo structure in go-ceph lacks that attribute.

Hmmm? Are you saying that state is missing? That shouldn't be a huge issue to add but if it is missing it might be because its not present on all ceph versions we support. Have you checked to see if it is available on nautilus?


BTW we enabled github discussions for go-ceph so that might be a good way to ask questions about how best to use apis when its not clear there's an actual issue (regarding the BytesQuota bit).

**Comment by phlogistonjohn** [comment]
Looking at the unit tests that exercise subvolume info, none of them have a "state" field. I suspect this was added in a backport and we weren't told about it. :-(

**Comment by agarwal-mudit** [comment]
Opened https://github.com/ceph/go-ceph/issues/454 and #453

**Comment by phlogistonjohn** [comment]
Now that the issues are split apart I'll close this issue as #452 has been merged.
