### ISSUE TITLE
Add String Method to admin.LevelSpec struct

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#522]
the `spec` field of the admin.LevelSpec is not exposed https://github.com/ceph/go-ceph/blob/4298c2bd0e9a77ae8161be6918d474c88a442405/rbd/admin/admin.go#L25 add a  `String` method to the LevelSpec which helps for both logging and the comparison when someone lists the snapshot schedules using https://github.com/ceph/go-ceph/blob/4298c2bd0e9a77ae8161be6918d474c88a442405/rbd/admin/msschedule.go#L62

**Comment by Madhu-1** [comment]
cc @phlogistonjohn @nixpanic

**Comment by nixpanic** [comment]
@Madhu-1 is there a particular format or details that you would like to see included?

For comparing, are you interested in sorting like time `Before()` and `After()`, or just an `Equals()` call?

**Comment by phlogistonjohn** [comment]
the "interior" type of a LevelSpec is a string, I suspect that @Madhu-1 just wants to be able to "see" that string.

As for comparison I hadn't even noticed the "and the comparison" part of @Madhu-1's request until you pointed it out @nixpanic. I don't know if there's a strong need to make these comparable but if there is let me know. I think adding a String method will suffice for "eyeballing" the LevelSpec values (I hope).

**Comment by Madhu-1** [comment]
and also adding `Equals()` will also make the things simple to compare the startTime,interval

**Comment by ansiwen** [comment]
@Madhu-1 For comparison, there is no need for a `Equal()` method. Structs with un-exported fields can still be compared and are equal, even if the string fields are not "identical" but only equal by value. So if you have  two `LevelSpec` values `ls1` and `ls2` you can simply compare with `ls1 == ls2`. If you need the a sting for logging, without any guarantees or structure, you can simply (like with `error` values) use `fmt.Sprintf("%v", ls1)` or `fmt.Sprintf("%+v", ls1)`. See https://play.golang.org/p/IGEHypCcsDZ

So, given that information, is there still something, that you actually need?

**Comment by Madhu-1** [comment]
@ansiwen yes agree for comparison I have to create two structures. and the way the spec is generated is something different with string concatenation https://github.com/ceph/go-ceph/blob/4298c2bd0e9a77ae8161be6918d474c88a442405/rbd/admin/admin.go#L31-L43 and the main intention was only to compare the LevelSpec.spec with a string, not any other fields (if it gets added in the future). 

This is not needed anymore at least for cephcsi.

**Comment by ansiwen** [comment]
@Madhu-1 I see, but that's already a first misunderstanding, because if another field would be added, I would expect it to be included in a general `String()` method. So, if you need specific information from that spec field, we might better store the information separately in the value and only create the string on demand. In fact I saw that coming and suggested that in the first place. 😜

**Comment by phlogistonjohn** [comment]
> @Madhu-1 I see, but that's already a first misunderstanding, because if another field would be added, I would expect it to be included in a general `String()` method. 

I agree. I see that a String method would be useful in informational contexts like logging & display (I know, the logging in golang can "peek" into the private fields of a struct but what if I'm building a GUI or something :-) ). But its not something you should expect to be 100% stable wrt the current output if fileds are added and removed.

> So, if you need specific information from that spec field, we might better store the information separately in the value and only create the string on demand. In fact I saw that coming and suggested that in the first place. stuck_out_tongue_winking_eye

Now I'm a tad confused, because that's the way it was being stored in the ye olde versions of my patch, but I also had a 2nd type as an "escape hatch" in case our implementation didn't 100% cover all use cases. Regardless, having private fields allows us flexibility and we're not stuck on the current impl. forever.

Do we need a String method now or in the short term future? If not, I suggest closing this issue and the related PR, and only revisiting this if we do need non-golang-logging display of a string repr of this type.

**Comment by phlogistonjohn** [comment]
So I just want to double check that we're all in general agreement that adding a String method is not required at this time? If so, we should close this issue and the associated PR.
Please confirm @Madhu-1. Silence will be taken as an implicit ack after a week. :-)

**Comment by Madhu-1** [comment]
@phlogistonjohn missed replaying on this one. we don't need this one for now in cephcsi maybe we can add it in future if we get requirement for it.
