### ISSUE TITLE
rgw: support more rgw admin API methods

### ISSUE THREAD

**Issue by maksim-kharitonov** [ceph/go-ceph#653]
add support of some useful methods of rgw admin API:

- get specific user's buckets with stats: [get-bucket-info](https://docs.ceph.com/en/latest/radosgw/adminops/#get-bucket-info)
- create/delete credentials: [create-key](https://docs.ceph.com/en/latest/radosgw/adminops/#create-key) [remove-key](https://docs.ceph.com/en/latest/radosgw/adminops/#remove-key)
- individual bucket quota support [set-quota-for-an-individual-bucket](https://docs.ceph.com/en/latest/radosgw/adminops/#set-quota-for-an-individual-bucket)

**Comment by sebastianriese** [comment]
Another thing that could be tackled while one is at it, is to use `/user?list` to list users (this endpoint exists at least for newer versions of ceph), instead of using `/metadata/user` – or otherwise document the reason the latter is preferred for some arcane reason. Sadly, neither endpoint is documented.

Also related (in that it adds more rgw admin ops methods: #644 )
