### ISSUE TITLE
Build failure calling rados connect function

### ISSUE THREAD

**Issue by ycsong1212** [ceph/go-ceph#771]
Hello, I am working on a project supporting ceph storage. Now I am trying to write a unit-test to validate the usability of ceph api using go-ceph repository. However, I failed to compile the project. It tells me that  
    undefined: rados.NewConn
    
It seems good in my Goland but I cannot compile it. This issue seems similar to https://github.com/ceph/go-ceph/issues/23. However, I tried to follow the function of changing CMakeList and make again. But I failed to complie librados and common module by cmake. I think I need help. I'll appreciate it if you could give a solution of calling function that could make me finish my test. Thank u~

**Comment by phlogistonjohn** [comment]
Note: I edited your comment to just enable word-wrap.

**Comment by phlogistonjohn** [comment]
So,  I'll try to help as I can but please be aware that our ability to help with any editor/IDE specific topics will probably be limited.

Next, I'm not sure where CMake/CMakeList comes into this picture. Normally, I'd expect to see (recent) Go codebases using go modules. In that case you'd have something like go.mod and go.sum in your repo.  Now, you may be wrapping or combing go with other stuff and using CMake at a higher level - if so, let's try to temporarily eliminate that from the process and use the go tool-chain directly if possible.

If you use the standard go tools you'll need to include go ceph in the go.mod file. This can usually be done using a command like `go get github.com/ceph/go-ceph`. This should insert the necessary lines in go.mod and go.sum so that the go compiler knows your Go code has a dependency on go-ceph and imports of go-ceph packages (like the `rados` package) come from this project.

I hope this gets you started.

**Comment by ycsong1212** [comment]
I am sure I have done ''go get" & "go mod tidy". If not, it is impossible to see it normally on my IDE. However, I failed to "go build" due to the issue I have reported. As is mentioned in issue #23, it seems that someone meet the similar issue. And at there someone said I need to change the CMakeList file in origin ceph repository https://github.com/ceph/ceph, but the function mentioned in issue #23 doesn't work. Therefore, I think I need your help for using APIs in go-ceph called by my other service. I'll appreciate it if you could help.

**Comment by ansiwen** [comment]
Several things are getting mixed up here, I think:

1. the error you see is an error about a missing go function, so it has nothing to do with librados.

2. if you deal with Cmake, then you are trying to compile _ceph_, and not go-ceph. (librados, librbd, etc.) If you need help with that, you need to ask in the ceph project, because we never do that. We always use the precompiled ceph-libraries from the distribution, and have no experience with compiling librados for example.

3. Issue #23 is about _static_ linking. Are you doing that? Why?

**Comment by ycsong1212** [comment]
I've already worked it out. I missed CGO_ENABLED flag to compile, thanks a lot.
