### ISSUE TITLE
VolumeStatus get failure through cephfs/admin

### ISSUE THREAD

**Issue by ycsong1212** [ceph/go-ceph#814]
Excuse me, I am trying to get volume status by VolumeStatus function in cephfs/admin package, my code is as follows,
```
package main

import (
	"fmt"
	"os/exec"

	"github.com/ceph/go-ceph/cephfs"
	cfa "github.com/ceph/go-ceph/cephfs/admin"
	"github.com/ceph/go-ceph/rados"
)

func main() {
	configFile := "/etc/ceph/ceph.conf"
	conn, err := rados.NewConn()
	if err != nil {
		fmt.Printf("create connect error: %v\n", err.Error())
		return
	}
	err = conn.ReadConfigFile(configFile)
	if err != nil {
		fmt.Printf("read config error: %v\n", err.Error())
		return
	}
	err = conn.Connect()
	if err != nil {
		fmt.Printf("connect to ceph cluster error: %v\n", err.Error())
		return
	}

	fa := cfa.NewFromConn(conn)
	fsList, err := fa.ListFileSystems()
	if err != nil {
		fmt.Printf("list fs err : %v\n", err.Error())
		return
	}
	fmt.Println(len(fsList))
	vs, err := fa.VolumeStatus("aip-test-volume")
	if err != nil {
		fmt.Printf("get volume status err : %v\n", err.Error())
		return
	}
	fmt.Println(len(vs.Pools))
	for _, pool := range vs.Pools {
		fmt.Printf("pool name is: %v, pool available is: %v, pool used is: %v\n", pool.Name, pool.Available, pool.Used)
	}
}
```
However, an error occurs,
get volume status err : rados: ret=-22, Invalid argument: "Traceback (most recent call last):\n  File \"/usr/share/ceph/mgr/mgr_module.py\", line 1757, in _handle_command\n    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)\n  File \"/usr/share/ceph/mgr/mgr_module.py\", line 462, in call\n    return self.func(mgr, **kwargs)\n  File \"/usr/share/ceph/mgr/status/module.py\", line 109, in handle_fs_status\n    assert metadata\nAssertionError\n"

It seems that My admin is created successfully referring to successfully get filesystem infos, however I failed to get volume status. Could you please help me with this problem? I'll appreciate it if you could help.

**Comment by phlogistonjohn** [comment]
That error is an internal error in the mgr being propagated back to our library. I have a couple of suggestions: 
* Provide the version of ceph running on your cluster
* Try and find the matching error in the mgr log
* See if you can reproduce it using an equivalent `ceph` CLI command call.  (See the "Similar To" line(s) in our API docs: https://pkg.go.dev/github.com/ceph/go-ceph@v0.19.0/cephfs/admin#FSAdmin.VolumeStatus)

I suspect the issue is server-side, but it might be triggered by something in our request. If we can eliminate go-ceph as a particular cause I'll suggest you reach out to the ceph team directly. But let's get that info first.

**Comment by ycsong1212** [comment]
> That error is an internal error in the mgr being propagated back to our library. I have a couple of suggestions:
> 
> * Provide the version of ceph running on your cluster
> * Try and find the matching error in the mgr log
> * See if you can reproduce it using an equivalent `ceph` CLI command call.  (See the "Similar To" line(s) in our API docs: https://pkg.go.dev/github.com/ceph/go-ceph@v0.19.0/cephfs/admin#FSAdmin.VolumeStatus)
> 
> I suspect the issue is server-side, but it might be triggered by something in our request. If we can eliminate go-ceph as a particular cause I'll suggest you reach out to the ceph team directly. But let's get that info first.

My ceph cluster's version is 17.2.5. My ceph client's version is 15.2.17. I have no access to the mgr log and I am trying to contact ceph SRE working on it. 
However, it seems that the command info is different from I expect. There is neither usage nor available field.
![image](https://user-images.githubusercontent.com/42312157/212636025-8882d836-568e-4ba8-800f-cd89ca37b741.png)
Is it normal? Or due to the failure of getting these necessary information, the result does not include fields that I expect.

**Comment by phlogistonjohn** [comment]
Thanks for the version numbers. Ceph 15.2.x (Octopus) is deprecated for go-ceph but it should work and we do continue to test it.

Try adding `--format=json` or `--format=json-pretty` to the command. 
Additionally, I don't think `ceph fs status takes more than one argument. Your screenshot says: `ceph status cephfs aip-test-volume`.  I only think one of `cephfs` or `aip-test-volume` is the name of your filesystem. 

So I'd try something like: `ceph fs status --format=json cephfs`. See what that returns.
Actually, try both names separately:
```
ceph fs status --format=json cephfs
ceph fs status --format=json aip-test-volume
```

See if the either encounters an error similar to the one you got using go-ceph calls. 


FWIW go-ceph always asks for JSON output from the mgr because the library parses the JSON response to return more granular types.

**Comment by ycsong1212** [comment]
> Thanks for the version numbers. Ceph 15.2.x (Octopus) is deprecated for go-ceph but it should work and we do continue to test it.
> 
> Try adding `--format=json` or `--format=json-pretty` to the command. Additionally, I don't think `ceph fs status takes more than one argument. Your screenshot says: `ceph status cephfs aip-test-volume`. I only think one of `cephfs`or`aip-test-volume` is the name of your filesystem.
> 
> So I'd try something like: `ceph fs status --format=json cephfs`. See what that returns. Actually, try both names separately:
> 
> ```
> ceph fs status --format=json cephfs
> ceph fs status --format=json aip-test-volume
> ```
> 
> See if the either encounters an error similar to the one you got using go-ceph calls.
> 
> FWIW go-ceph always asks for JSON output from the mgr because the library parses the JSON response to return more granular types.

I have tried these two command and I have met similar problem as follow,
![image](https://user-images.githubusercontent.com/42312157/213068203-8cd6f0a7-7627-4ec7-bd8a-2c897b9ac3ca.png)
However, what is strange that the line number shown in error log is different from the same in my container. And ourceph SRE is still not working on it. I will push him. 
Besides, I find that 'ceph fs volume info' command can meet my requirement.
![image](https://user-images.githubusercontent.com/42312157/213068827-a302301d-c741-4d88-aba3-5e896da8a715.png)
I do not find this API, so have we got interface supporting this command, maybe in a test version? Or, could you provide a template to develop adding methods supporting new command?

**Comment by ycsong1212** [comment]
> 

I have implemented function calling 'ceph fs volume info' and I could get useful information I expect. Is this command support in the plan providing with go-ceph users?

**Comment by phlogistonjohn** [comment]
Since you can reproduce the error with just the `ceph` cli tool, I suggest you report a new issue at the ceph tracker: https://tracker.ceph.com/

At the very least, even if this is expected to be an error condition, the ceph team may want to produce a more helpful error message. 

Since yours is the only cluster I know of that hits this error I don't think there's anything in particular go-ceph needs to do at the moment. This function passes our CI and I assume is working for other consumers. Feel free to report back here what the ceph devs say if you think it is interesting/relevant to go-ceph.

**Comment by ycsong1212** [comment]
> Since you can reproduce the error with just the `ceph` cli tool, I suggest you report a new issue at the ceph tracker: https://tracker.ceph.com/
> 
> At the very least, even if this is expected to be an error condition, the ceph team may want to produce a more helpful error message.
> 
> Since yours is the only cluster I know of that hits this error I don't think there's anything in particular go-ceph needs to do at the moment. This function passes our CI and I assume is working for other consumers. Feel free to report back here what the ceph devs say if you think it is interesting/relevant to go-ceph.

OK, I got it, thx~

**Comment by phlogistonjohn** [comment]
https://tracker.ceph.com/issues/57072

Looks like the same issue. I saw the PR for this just now (pacific backport), so depending on your server version there may already be a fix available or you can wait for the next pacific release.

**Comment by ycsong1212** [comment]
> https://tracker.ceph.com/issues/57072
> 
> Looks like the same issue. I saw the PR for this just now (pacific backport), so depending on your server version there may already be a fix available or you can wait for the next pacific release.

It seems that someone have fixed this bug. Thanks for your help.
![image](https://user-images.githubusercontent.com/42312157/216915390-347265e2-303b-4980-9a97-81a106dcdf30.png)
