### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by QZB349549482** [ceph/go-ceph#822]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/48619923/215697627-900a898d-1918-4e4c-a77f-ae3d73a9351c.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/48619923/215697741-2e7d3887-d46e-411f-9bcb-44ddc09565ae.png">

As the picture , I want to MakeDir ,and the error response, but i have got the currentDir . Is there some error or 
I should make some advance preparation ?

**Comment by phlogistonjohn** [comment]
I agree, that does seem a bit puzzling. One thing that would help is a better idea of what fsConnect functions are doing.

Additionally, I wonder if ceph libraries are returning a confusing error code. See the end section of [this blog post](http://asynchrono.us/how-i-work-on-go-ceph.html) for some more information on setting debug options for the ceph libraries. Try setting some of the components to level 20 in order to see what the ceph libraries are doing.

**Comment by phlogistonjohn** [comment]
PS: If you share more code please paste it (ideally [between triple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)) rather than using screenshots. Thanks!

**Comment by QZB349549482** [comment]
It is work after up the MDS in the cluster
