### ISSUE TITLE
Question : MountWithRoot() mounts any directory

### ISSUE THREAD

**Issue by adroitperson37** [ceph/go-ceph#868]
Issue : 

Client with a keyring file (which has access to only certain directory) is used to create a mount . Then when MountWithRoot() is provided with a different directory the call succeeds without any error. Is it the behavior ? How can I use mount in such a way that when I create a client connection (which has access to only certain directory) the connection will only be able to mount what is authorized to this client but not other directories?

**Comment by phlogistonjohn** [comment]
Interesting question,

> Client with a keyring file (which has access to only certain directory) is used to create a mount . Then when MountWithRoot() is provided with a different directory the call succeeds without any error. 

Do file operations on that dir (new root) succeed? Stuff like stat/mkdir/read/write/etc?


> Is it the behavior ? How can I use mount in such a way that when I create a client connection (which has access to only certain directory) the connection will only be able to mount what is authorized to this client but not other directories?

To be honest I'm not sure, in this regard go-ceph is largely acting as a as a layer on top of the cephfs C apis. We will sometimes tweak APIs to make them better match idomatic go, but for something like this where there's a question of underyling API behavior I suggest reaching out to the cephfs team directly.  Good resources to use are the [ceph mailing lists](https://ceph.io/en/community/connect/) or [ceph issue tracker](https://tracker.ceph.com/).

Feel free to keep us in the loop because I would like to know more too, and there's the chance someone else will ask a similar question in the future.

**Comment by phlogistonjohn** [comment]
> I see. let me reiterate what you said with an example?
> 
>     1. I mounted a directory called /foo[assume it exists in cephfs] with mountInfo.MountWithRoot("/foo")
> 

OK

>     2. lets say about call succeed and when I do mountInfo.IsMount()  I get true.
> 

I assume you mean `IsMounted`.  If so, yes, that seems right.

>     3. when I do mountInfo.StatFS("/") I should be able to get the fsid of that ceph directory? I go -1 here when I tried mountInfo.StatFS("/") or mountInfo.StatFS("/foo")
> 

StatFS is a different call from Statx. I checked the code and yes it appears you can get the fsid from that call, do note that it is returned as an integer, not as the familiar string form you usually see it as in ceph. So I'm not sure that they are the same "fsid".

If you're still running the API with a resricted user it may be possible that StatFS is not allowed. I dunno for sure I've never experimented with that in the past.


> 
> Also is there an option to do system level mount those ceph directories using this api?

No, we wrap the APIs provided by ceph's libcephfs which is a pure userspace layer. If you need to have a system level mount you can mount cephfs [using the built in kernel module](https://docs.ceph.com/en/latest/cephfs/mount-using-kernel-driver/) or fuse. The former is more common. If you choose to mount cephfs via the kernel you can then use Go's standard library APIs for interacting with the file system (io/fs and os packages for example).
