### ISSUE TITLE
How to call OSD BLACKLIST?

### ISSUE THREAD

**Issue by AmazingPangWei** [ceph/go-ceph#872]
I'm pretty confused that there is not enough docs for learning go-ceph. I want to use it to add a osd blacklist, like `ceph osd blacklist add` , but I didn't see any docs or examples. 

So, what is the proper way to do this?

**Comment by phlogistonjohn** [comment]
I'm sorry to hear that you find our docs insufficient.

We have not implemented any APIs specific to the `ceph osd blocklist` (nee blacklist) commands. However, almost all `ceph` cli commands are implemented by sending JSON commands to one of [rados.MgrCommand](https://pkg.go.dev/github.com/ceph/go-ceph@v0.21.0/rados#Conn.MgrCommand) or [rados.MonCommand](https://pkg.go.dev/github.com/ceph/go-ceph@v0.21.0/rados#Conn.MonCommand). Knowing what JSON to send is the sometimes tricky part because it's not clearly documented either, but can be determined by a sending a special JSON `{"prefix": "get_command_descriptions"}` to the API which dumps the list of "endpoints".

So you can either put in a request that we write Go APIs for these blocklist related ceph features or you can try writing something that makes use of rados APIs directly and then you don't need to wait for us to get to it.

See also https://github.com/ceph/go-ceph/issues/598 and https://github.com/ceph/go-ceph/pull/626

**Comment by phlogistonjohn** [comment]
I also just remembered that there's a librados C API related to this as well:
https://github.com/ceph/ceph/blob/d9e6e1de796bccd81bfbb50bc461c2d5ecb19c7f/src/include/rados/librados.h#L3736-L3743

I'm not clear on the relationship between the `ceph` command and the C-api (if they do the same thing) because I have not researched this topic much myself.

**Comment by AmazingPangWei** [comment]
@phlogistonjohn Thanks for your reply. I just tested [rados.MonCommand](https://pkg.go.dev/github.com/ceph/go-ceph@v0.21.0/rados#Conn.MonCommand) by sending `{"prefix": "get_command_descriptions"}`, and found `ceph osd blocklist` command successfully.  You my friend, are a true hero.

I think it's a good way to mention this part to docs (such as [hints.md](https://github.com/ceph/go-ceph/blob/master/docs/hints.md)), which is helpful for beginner, like me.

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn Thanks for your reply. I just tested [rados.MonCommand](https://pkg.go.dev/github.com/ceph/go-ceph@v0.21.0/rados#Conn.MonCommand) by sending `{"prefix": "get_command_descriptions"}`, and found `ceph osd blocklist` command successfully. You my friend, are a true hero.
> 

Thanks for the kind words.

> I think it's a good way to mention this part to docs (such as [hints.md](https://github.com/ceph/go-ceph/blob/master/docs/hints.md)), which is helpful for beginner, like me.

Yes, I agree. I will keep this issue open to serve as a TODO to document this and some related topics.
