### ISSUE TITLE
API call to set image QoS

### ISSUE THREAD

**Issue by almottier** [ceph/go-ceph#988]
Hello,

I am looking for an API call to set and get QoS image configuration. Specifically, I would like to perform the equivalent of the following CLI commands via the API:

```
rbd config image set myimage rbd_qos_iops_limit 5000
rbd config image get myimage rbd_qos_iops_limit
```

Is it currently possible to achieve this through the go-ceph API?

**Comment by phlogistonjohn** [comment]
I think [SetMetadata](https://github.com/ceph/go-ceph/blob/be5dff01c98adebe5b4de4f159f7629eb821fb3a/rbd/metadata.go#L48) and GetMetadata are the functions you want for this.  You may need to prefix the key with "conf_" because that's what the rbd command line code appears to do: https://github.com/ceph/ceph/blob/25e4ee2fa7e8913bac09af9e43706ddeba1cd14a/src/tools/rbd/action/Config.cc#L480

**Comment by almottier** [comment]
Thank you @phlogistonjohn, that's exactly what I was looking for!
